version: "3.7"
networks:
  travellist:
    driver: bridge

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: ${DOCKER_NAME_PREFIX}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db4:
    image: mysql:8.0
    container_name: ${DOCKER_NAME_PREFIX}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - travellist
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: ${DOCKER_NAME_PREFIX}-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db4
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db4
    networks:
      - travellist
    
  nginx:
    image: nginx:alpine
    container_name: ${DOCKER_NAME_PREFIX}-nginx
    restart: unless-stopped
    ports:
      - ${DOCKER_APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - travellist
    depends_on:
      - app